### ISSUE TITLE
Typescript: Have static methods return the proper types

### ISSUE THREAD

**Issue by NoelDeMartin** [NoelDeMartin/soukai#1]
Typescript declarations for static model operations are defined as follows:

```ts
public static all<T extends Model>(): Promise<T[]>;
```

Meaning that all models will have a static method named `all` that returns an array of models. But there is a limitation with this. For example, imagine having a `Task` model, and retrieving a list of tasks as such:

```ts
Task.all().then(tasks => {
    // Do things with tasks
}
```
In this scenario, the tasks argument will be typed as a generic `Model[]`, so in order to get the proper types it should be called like this:

```ts
Task.all<Task>().then(tasks => {
    // Now you can access Task-specific type definitions
}
```

Which is tedious and repetitive, so it'd be great to have types defined automatically, without having to rewrite definitions for each model class. But I'm not sure this is possible with typescript at the moment.

**Comment by NoelDeMartin** [comment]
Ok, I'm trying something for [hacktoberfest](https://hacktoberfest.digitalocean.com/) this year :).

If anyone participating in hacktoberfest wants to help, I could really do with some help if there is any Typescript wizards out there. Essentially, I'd like to declare a method using a static return type declaration, similar to what is introduced here for PHP: https://wiki.php.net/rfc/static_return_type

Here's a simplified version of the problem I'm trying to solve:

```ts
abstract class Model {

    // I would like to declare this as "public static all(): static[]" instead, but I'm not sure how to do that.
    public static all(): Model[] {
        return [
            new this(),
            new this(),
            new this(),
        ];
    }

}

class Task extends Model {

    // I want to avoid doing this in every subclass.
    // This class already has the all method, but its return type is Model.
    // I'm only adding this here so that the return type is Task (or whatever the subclass is).
    public static all(): Task[] {
        return this.all();
    }

}
```

It'd also help me to know that this isn't possible, but I don't know enough about Typescript to be sure.

**Comment by R0DR160HM** [comment]
Hello, I just opened a pr where I created a decorator that allows you to implement the static Model.all method in a simple way. I apologize in advance if there was any misunderstanding and the problem was not really this.

**Comment by NoelDeMartin** [comment]
Hi @R0DR160HM thanks for your help!

I don't think what you propose solves the problem, the subclass already has the all() method. I'm only implementing it in the subclass to change the declaration of the return type. I've updated my comment with more details to make it less confusing.

In particular, what I want is something called "static return type" in PHP: https://wiki.php.net/rfc/static_return_type

**Comment by NoelDeMartin** [comment]
It seems this is already a [known issue](https://github.com/Microsoft/TypeScript/issues/5863) in Typescript, with my exact use case.

**Comment by NoelDeMartin** [comment]
I finally managed to do it :D I've also added improved [TypeScript inference](https://soukai.js.org/guide/defining-models.html#typescript-inference) in the latest release, so I'm closing this.
